# Generated by Django 4.1.1 on 2022-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
