# Generated by Django 4.1.1 on 2022-09-22 05:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
